<a href="https://colab.research.google.com/github/sharvilpawar123-source/pandas-data-analysis/blob/main/GroupByAggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
data={
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range('2023-01-01', periods=8)

}

df = pd. DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [24]:
# gp by catagory and sum of sells
a =df.groupby('Category')
a

In [25]:
for i,v in a:
  print(i)
  print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [26]:
a =df.groupby('Category')['Sales'].sum()
a

Category
A    570
B    930
Name: Sales, dtype: int64

In [27]:
# gp by stores and calc sum of sales
b =df.groupby('Store')['Sales'].sum()
b

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [30]:
# gp by multiple columns like gp by store and catagory
c =df.groupby(['Category','Store'])['Sales'].sum()
c

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#Aggregation - multiple chizo ko sath me combine karna

In [32]:
df['Sales'].mean() # mean ,median ,mode, min, max, count, std

np.float64(187.5)

In [33]:
df['Sales'].agg(['mean','median','min','max','count','std'])  #multiple val ar one time

mean      187.500000
median    190.000000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64