<a href="https://colab.research.google.com/github/sharvilpawar123-source/pandas-data-analysis/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

#Series

In [3]:
labels=["a","b","c"]
list=[10,20,30]
arr=np.array(list)
dict={1:10,2:20,3:30}

In [7]:
pd.Series(list)

1    10
2    20
3    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

# DataFrames

In [11]:
data={

'Name': ['John', 'Anna', 'Peter', 'Linda'],
'Age': [28, 34, 29, 42],
'City': ['New York', 'Paris', 'Berlin', 'London'],
 'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
data_list =[
['John', 28, 'New York', 65000],
['Anna', 34,'Paris', 70000],
['Peter',29,'India',50000],
['Linda',42,'London',85000]
]
# df2=pd.DataFrame(data_list)
# df2
df=pd.DataFrame(data_list,columns=['Name','Age','City','Salary'])
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29     India   50000
3  Linda   42    London   85000

#Columns

In [21]:
df[['City','Name']]

       City   Name
0  New York   John
1     Paris   Anna
2     India  Peter
3    London  Linda

In [34]:
# to add new col
df["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [35]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29     India   50000      Doctor
3  Linda   42    London   85000        Eng.

In [36]:
df.drop('Designation',axis=1)
# it completely remove designation col
# df.drop('Designation',axis=1,inplace=True)

In [38]:
df.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29   India   50000
3  Linda   42  London   85000

#Rows

In [40]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [41]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [43]:
# select perticular area
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [45]:
# Conditional
df[df['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [48]:
df[(df['Age']>30)&(df['Salary']>70000)]

    Name  Age    City  Salary
3  Linda   42  London   85000

# Finding Missing Data

In [5]:
import numpy as np
import pandas as pd
data = {
'A': [1, 2, np.nan, 4, 5],
'B': [np.nan, 2, 3, 4,5],
'C': [1, 2, 3, np.nan, np.nan],
'D':[1, np.nan, np.nan, np.nan, np.nan]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [6]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True   True

In [7]:
df.isna().sum()   #total null val in each row

A    1
B    1
C    2
D    4
dtype: int64

In [8]:
df.isna().any() # har ek row me NULL val he kya cheack karega

A    True
B    True
C    True
D    True
dtype: bool

In [9]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  NaN

In [10]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [12]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN

In [13]:
# fill all null with 0
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  0.0

In [15]:
# # fill all null with diff vals
val={'A':0,'B':1,'C':2,'D':3}
df.fillna(value=val)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  0.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  3.0

# merging ans sorting

In [16]:
employees= pd.DataFrame({
'employee_id': [1, 2, 3, 4, 5],
'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
'department': ['HR', 'IT', 'Finance', 'IT','HR'],

})

# DataFrame 2: Salary information

salaries = pd.DataFrame({
'employee_id': [1, 2, 3, 6, 7],
'salary': [60000, 80000, 65000, 70000, 90000],
'bonus': [5000, 10000, 7000, 8000, 12000]})

In [17]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [18]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [20]:
pd.merge(employees,salaries,on='employee_id',how='outer')
# pd.merge(employees,salaries,on='employee_id',how='left')
# pd.merge(employees,salaries,on='employee_id',how='right')
# pd.merge(employees,salaries,on='employee_id',how='inner')
# pd.merge(employees,salaries,on='employee_id',how='cross')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

#Concatination

In [23]:
df1 = pd.DataFrame({

'A':['A0','A1','A2'],
'B':  ['B0','B1','B2'],
'C':['C0','C1','C2']

})

df2 = pd.DataFrame({

'A':['A3','A4','A5'],
'B':  ['B3','B4','B5'],
'C':['C3','C4','C5']

})

df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [24]:
pd.concat([df1,df2])#on the basis of col

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [25]:
pd.concat([df1,df2],axis=1)#on the basis of row

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#joining two data frames

In [27]:
df1 = pd.DataFrame({
'name':['Alice','Bob','Charlie']

}, index=[1, 2, 3])

# Second DataFrame

df2 = pd.DataFrame({'score': [85, 90, 75]

},index=[2,3, 4])
df1

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75

In [30]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [31]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0